spring:
  datasource:
    username: ${USER:user}
    password: ${PASSWORD:password}
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/test-db}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
